# Generated by Django 5.0.3 on 2024-03-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
